### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by ljhwang** [bch0w/pyatoa#1]
Congratulations on putting together this workflow.  It will be exciting to see how this is adopted by the community. 

We recommend that you place a LICENSE file in the main directory of your repo to tell users how the software is allowed to be used.  For open source software, we usually recommend GPL: https://opensource.org/licenses/gpl-license.  This could be complicated by conflicts in downstream licenses.  

An implementation of this can be found here: 
https://github.com/geodynamics/aspect

For more best practices see the Contributing Software Checklist here:
https://github.com/geodynamics/best_practices

**Comment by bch0w** [comment]
I'm one year late on the response here but thank you for this recommendation, and the provided resources, Lorraine! License file has been added and Pyatoa will strive to follow best practices outlined by CIG.
